// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXw4We7uSkQYBL7PDe44IoL3M_7bKHufE',
    appId: '1:790846208848:android:370f0062d450dca6ba8a55',
    messagingSenderId: '790846208848',
    projectId: 'aplikasi-rt-949ce',
    storageBucket: 'aplikasi-rt-949ce.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjF64LZ87Oz9KL-hY_qBUWS1FNBr9g2yE',
    appId: '1:790846208848:web:0a8a21a24fe85d96ba8a55',
    messagingSenderId: '790846208848',
    projectId: 'aplikasi-rt-949ce',
    authDomain: 'aplikasi-rt-949ce.firebaseapp.com',
    storageBucket: 'aplikasi-rt-949ce.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuujW1IKp44BCmdnvcaJb_xb1HyRbP044',
    appId: '1:790846208848:ios:3d7b4f5117b9e07cba8a55',
    messagingSenderId: '790846208848',
    projectId: 'aplikasi-rt-949ce',
    storageBucket: 'aplikasi-rt-949ce.firebasestorage.app',
    iosBundleId: 'com.example.rtAppApk',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuujW1IKp44BCmdnvcaJb_xb1HyRbP044',
    appId: '1:790846208848:ios:3d7b4f5117b9e07cba8a55',
    messagingSenderId: '790846208848',
    projectId: 'aplikasi-rt-949ce',
    storageBucket: 'aplikasi-rt-949ce.firebasestorage.app',
    iosBundleId: 'com.example.rtAppApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjF64LZ87Oz9KL-hY_qBUWS1FNBr9g2yE',
    appId: '1:790846208848:web:7570654adeb7cf36ba8a55',
    messagingSenderId: '790846208848',
    projectId: 'aplikasi-rt-949ce',
    authDomain: 'aplikasi-rt-949ce.firebaseapp.com',
    storageBucket: 'aplikasi-rt-949ce.firebasestorage.app',
  );

}